version: "3"
services:
  postgres:
    container_name: keycat_pg
    image: postgres:alpine
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycat_dev
